apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  symfony.local.conf: |
    server {
         root /srv/app/public;
    
         location / {
             try_files $uri @rewriteapp;
         }
    
         location @rewriteapp {
             rewrite ^(.*)$ /index.php/$1 last;
         }
         
        large_client_header_buffers 4 32k;
        client_max_body_size 20M;
    
        gzip on;
        gzip_disable "msie6";
        gzip_http_version 1.1;
        gzip_comp_level 3;
        gzip_min_length 256;
        gzip_vary on;
        gzip_proxied any;
        gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript application/javascript application/vnd.ms-fontobject application/x-font-ttf font/opentype image/svg+xml image/x-icon;
    
         location ~ ^/index\.php(/|$) {
             #fastcgi_pass php:9000;
             fastcgi_pass 127.0.0.1:9000;
             fastcgi_split_path_info ^(.+\.php)(/.*)$;
             include fastcgi_params;
             fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
             fastcgi_param HTTPS off;
             fastcgi_ignore_client_abort on;
             fastcgi_send_timeout 1200;
             fastcgi_read_timeout 1200;
             fastcgi_buffers 32 32k; 
             fastcgi_buffer_size 64k;
         }
         
         location ~ ^/(status|ping)$ {
             #access_log off;
             allow 127.0.0.1;
             allow 172.17.0.0/24;
             deny all;
             include fastcgi_params;
             fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
             fastcgi_pass 127.0.0.1:9000;
         }
    }
